# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-362ec972-7c5e-4c9f-ba5d-b8f2ed083509";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-362ec972-7c5e-4c9f-ba5d-b8f2ed083509".device =
    "/dev/disk/by-uuid/362ec972-7c5e-4c9f-ba5d-b8f2ed083509";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/27EE-D950";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/drives/aleph" = {
    device = "/dev/disk/by-uuid/e9ea0612-282f-4462-b9a5-9d9488e45bca";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/mapper/luks-af320a0f-b388-43f5-b5a3-af2b47cfc716"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
